### ISSUE TITLE
No Input Accepted in Parallels 12/13

### ISSUE THREAD

**Issue by marmanold** [shidel/FDIMPLES#1]
When running under Parallels Desktop under FreeDos 1.2 FDIMPLES does not accept keyboard input and is unusable.
I would love to help debug this issue, but do not know where to start.
Keyboard input is accepted under DZ.exe and other tools, so I do not think it is a keyboard driver issue.

**Comment by shidel** [comment]
Thank you for your report. Since other virtual machines and physical systems have not exhibited this issue running FDIMPLES, my first though is that this is a compatibility problem that is caused by an incomplete or improper implementation of parts of the legacy PC BIOS in the Parallels VM software. However, this does not mean that FDIMPLES can't work around the problem. Or, it is possible there is a bug in FDIMPLES that only occurs under Parallels. 

At present, FDIMPLES was built in Turbo Pascal quickly to serve an immediate need shortly before the FreeDOS 1.2 release. It uses a version of my 20+ year old QCrt called QCrtNM (mouse handling stripped out). This library provides backward compatibility with the original (but broken) Borland Crt unit. It is also much faster and provides more advanced features. One such feature is an event engine to handle all user input. Keyboard input is handled through seizing control of multiple BIOS and DOS interrupts. Also, it checks BIOS variables to determine wether or not to use basic or advanced 101 key keyboard methods. At some point, when I have the time, I intend on rebuilding the entire thing in assembly. 

Anyhow, I created a version that limits itself to use only the basic BIOS keyboard  functions to see if that resolves the issue. https://dnld.lod.bz/FDIMPLES-TEST.zip

**Comment by marmanold** [comment]
Thanks for the test version!  Unfortunately, it still exhibits the same issue.

My guess is that you are correct and Parallels just has an odd BIOS that doesn't fully work as it should.

**Comment by shidel** [comment]
Thanks for checking. QCrt(NM) takes control of a lot of low level stuff. So, the issue may be through some of the other low level processes that it  grabs control of when running. For example, QCrt also powers PGME. PGME will freeze a few seconds after startup on PC-DOS. I think that issue is due to PC-DOS not implementing some interrupts exactly to the MS-DOS specifications.

When I rewrite FDIMPLES in asm, it will be less forceful. More like how the keyboard is handled in V8Power Tools (utilities that drive the FreeDOS 1.2 installer). They handle the keyboard in a simpler, more robust and universally support manor. 

I just created another new test https://dnld.lod.bz/FDIMPLES-TEST2.zip

This version uses a more modern and purely assembly version of the QCrt unit. I then stripped down QCrtNM to only include some additional functionality (Like event handling objects) and some minor other stuff for compatibility with FDIMPLES. This version may work for you.

 (Note: some things like specifying filenames for loading and saving change file lists will not work in this version. Trying to load or save those files, by pressing the R & W keys, will cause it to freeze. But, basic functionality works fine.)

**Comment by marmanold** [comment]
That did the trick!  Fully functional now.  Thanks!

**Comment by dskr99** [comment]
Hi, I'm one of the Parallels Developer, I believe we have found a small problem in our bios that caused the issue. I may not say whether and when the fix will be delivered, but it was interesting to debug and fix it.

**Comment by shidel** [comment]
I'm glad to hear you were able to isolate the issue. I realize that "Legacy" DOS support is not a very high priority nowadays. Hopefully, the patch will make it into future updates to Parallels.

**Comment by marmanold** [comment]
Seriously @dskr99 , this is great!  Excited to see it make its way into a future update.
